[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "4.1.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  branch = "v2"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"
